[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Jackson Riley <jackson.riley@btinternet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_scan = "0.4"
regex = "1"